### ISSUE TITLE
YUV2RGBA 这个方法是不是会造成图像颜色的丢失呢？试用了一下发现，使用YUV2RGBA生成的bitmap和相机预览的图像在颜色上还是有差别的

### ISSUE THREAD

**Issue by gejiashu** [bookzhan/bzyuvlib#1]
![Screenshot_20200620-130758](https://user-images.githubusercontent.com/7670817/85193106-e234d180-b2f7-11ea-90af-d4642db48f7a.png)
比如这张照片，颜色差别就很大

**Comment by gejiashu** [comment]
猜测可能是使用YUV420格式数据和预览不一样的问题，估计采用YUV444就会没有问题了，请假一下如何使用libyuv把yuv444转换成rgba的格式呢？

**Comment by bookzhan** [comment]
> ![Screenshot_20200620-130758](https://user-images.githubusercontent.com/7670817/85193106-e234d180-b2f7-11ea-90af-d4642db48f7a.png)
> 比如这张照片，颜色差别就很大



> ![Screenshot_20200620-130758](https://user-images.githubusercontent.com/7670817/85193106-e234d180-b2f7-11ea-90af-d4642db48f7a.png)
> 比如这张照片，颜色差别就很大

这个是Google libyuv出来的数据，首先从yuv到rgba是从小的数据量到大的数据量的转换，本身就会有信号失真的情况。如果你很介意一般来说从yuv转换到rgba是有一个公式的，可以修改这个公式来达到你想要的。另外你用这个手机试一下通过Camera调用拍照，看看拍出的照片是不是也是这样，如果也是这样，我觉得你可以忽略这个问题

**Comment by bookzhan** [comment]
> 猜测可能是使用YUV420格式数据和预览不一样的问题，估计采用YUV444就会没有问题了，请教一下如何使用libyuv把yuv444转换成rgba的格式呢？

AndroidCamera输出的数据是不支持yuv444的

**Comment by gejiashu** [comment]
试了一下，用系统的相机去拍照，预览效果，和实际拍出来的效果也是存在一些色差的。改了一下Camera2的格式YUV444确实没有画面输出，多谢
