### ISSUE TITLE
libyuv这个库发生了native crash不是必现的，有遇到吗

### ISSUE THREAD

**Issue by gejiashu** [bookzhan/bzyuvlib#2]
![微信图片_20200622123858](https://user-images.githubusercontent.com/7670817/85249133-86984e80-b485-11ea-9005-6a5c807276ad.jpg)

**Comment by bookzhan** [comment]
你把日志贴上来，你的图挂掉了

**Comment by gejiashu** [comment]
A/DEBUG: signal 11 (SIGSEGV), code 2 (SEGV_ACCERR), fault addr 0xc967a000
A/DEBUG:     r0  b5afbc00  r1  b5bd9340  r2  b5c57c40  r3  c9679fec
A/DEBUG:     r4  d6e75030  r5  d6e75054  r6  d6e75060  r7  ffba5718
A/DEBUG:     r8  000005a0  r9  d6e6af75  r10 b5bd92c0  r11 00000780
A/DEBUG:     ip  00000338  sp  ffba56f8  lr  d6e75040  pc  d6e6b024
A/DEBUG: backtrace:
A/DEBUG:     #00 pc 00018024  /data/app/com.packagename--khlULmYeRPiCaH7l4qbUg==/lib/arm/libbzyuvlib.so (I422ToARGBRow_NEON+176)
A/DEBUG:     #01 pc 0000b8ff  /data/app/com.packagename--khlULmYeRPiCaH7l4qbUg==/lib/arm/libbzyuvlib.so (I420ToARGB+134)
A/DEBUG:     #02 pc 00008e7b  /data/app/com.packagename--khlULmYeRPiCaH7l4qbUg==/lib/arm/libbzyuvlib.so (handle_conversion(unsigned char*, unsigned char*, unsigned char*, unsigned char*, int, int, bool, int, Pix_Format)+354)
A/DEBUG:     #03 pc 0000917d  /data/app/com.packagename--khlULmYeRPiCaH7l4qbUg==/lib/arm/libbzyuvlib.so (pretreatmentYuv420pData(_JNIEnv*, _jclass*, _jobject*, int, _jobject*, int, int, _jobject*, int, int, _jbyteArray*, int, int, unsigned char, int, Pix_Format)+644)
A/DEBUG:     #04 pc 00009225  /data/app/com.packagename--khlULmYeRPiCaH7l4qbUg==/lib/arm/libbzyuvlib.so (Java_com_luoye_bzyuvlib_BZYUVUtil_yuv420pToRGBA+56)
A/DEBUG:     #05 pc 00411a79  /system/lib/libart.so (art_quick_generic_jni_trampoline+40)
A/DEBUG:     #06 pc 0040d575  /system/lib/libart.so (art_quick_invoke_stub_internal+68)
A/DEBUG:     #07 pc 003e6c93  /system/lib/libart.so (art_quick_invoke_static_stub+222)
A/DEBUG:     #08 pc 000a1027  /system/lib/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+154)
A/DEBUG:     #09 pc 001e5ae9  /system/lib/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+236)
A/DEBUG:     #10 pc 001e1415  /system/lib/libart.so (bool art::interpreter::DoCall<true, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+608)
A/DEBUG:     #11 pc 003e39e9  /system/lib/libart.so (MterpInvokeStaticRange+100)
A/DEBUG:     #12 pc 00400794  /system/lib/libart.so (ExecuteMterpImpl+15380)
A/DEBUG:     #13 pc 004cdb4e  /dev/ashmem/dalvik-classes.dex extracted in memory from /data/app/com.packagename--khlULmYeRPiCaH7l4qbUg==/base.apk (deleted) (com.luoye.bzyuvlib.BZYUVUtil.yuv420pToRGBA+198)
A/DEBUG:     #14 pc 001c4d53  /system/lib/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.841527758+378)
A/DEBUG:     #15 pc 001c937f  /system/lib/libart.so (art::interpreter::EnterInterpreterFromEntryPoint(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*)+82)
A/DEBUG:     #16 pc 003d52d1  /system/lib/libart.so (artQuickToInterpreterBridge+880)
A/DEBUG:     #17 pc 00411aff  /system/lib/libart.so (art_quick_to_interpreter_bridge+30)
A/DEBUG:     #18 pc 000e003d  /dev/ashmem/dalvik-jit-code-cache (deleted) (com.packagename.camera.Camera2Controller.lambda$startCaptureSession$0$Camera2Controller+348)
A/DEBUG:     #19 pc 000e22c3  /dev/ashmem/dalvik-jit-code-cache (deleted) (com.packagename.camera.-$$Lambda$Camera2Controller$pEW1vY94SrCJ_i_YIKKjorQRAzQ.onImageAvailable+50)
A/DEBUG:     #20 pc 000a692f  /dev/ashmem/dalvik-jit-code-cache (deleted) (android.media.ImageReader$ListenerHandler.handleMessage+286)
A/DEBUG:     #21 pc 0008d117  /dev/ashmem/dalvik-jit-code-cache (deleted) (android.os.Handler.dispatchMessage+126)
A/DEBUG:     #22 pc 000e2b15  /dev/ashmem/dalvik-jit-code-cache (deleted) (android.os.Looper.loop+892)
A/DEBUG:     #23 pc 0040d5bb  /system/lib/libart.so (art_quick_osr_stub+42)
A/DEBUG:     #24 pc 0024aa39  /system/lib/libart.so (art::jit::Jit::MaybeDoOnStackReplacement(art::Thread*, art::ArtMethod*, unsigned int, int, art::JValue*)+1388)
A/DEBUG:     #25 pc 003e61c3  /system/lib/libart.so (MterpMaybeDoOnStackReplacement+86)
A/DEBUG:     #26 pc 0040cdf4  /system/lib/libart.so (ExecuteMterpImpl+66164)
A/DEBUG:     #27 pc 00aecb7c  /system/framework/boot-framework.vdex (android.os.Looper.loop+928)
A/DEBUG:     #28 pc 001c4d53  /system/lib/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.841527758+378)
A/DEBUG:     #29 pc 001c9439  /system/lib/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+152)
A/DEBUG:     #30 pc 001e05bf  /system/lib/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+790)
A/DEBUG:     #31 pc 003e27c7  /system/lib/libart.so (MterpInvokeStatic+130)
A/DEBUG:     #32 pc 00400494  /system/lib/libart.so (ExecuteMterpImpl+14612)
A/DEBUG:     #33 pc 00385b2a  /system/framework/boot-framework.vdex (android.app.ActivityThread.main+214)
A/DEBUG:     #34 pc 001c4d53  /system/lib/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.841527758+378)
A/DEBUG:     #35 pc 001c937f  /system/lib/libart.so (art::interpreter::EnterInterpreterFromEntryPoint(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*)+82)
A/DEBUG:     #36 pc 003d52d1  /system/lib/libart.so (artQuickToInterpreterBridge+880)
A/DEBUG:     #37 pc 00411aff  /system/lib/libart.so (art_quick_to_interpreter_bridge+30)
A/DEBUG:     #38 pc 0040d575  /system/lib/libart.so (art_quick_invoke_stub_internal+68)
A/DEBUG:     #39 pc 003e6c93  /system/lib/libart.so (art_quick_invoke_static_stub+222)
A/DEBUG:     #40 pc 000a1027  /system/lib/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+154)
A/DEBUG:     #41 pc 00347ac5  /system/lib/libart.so (art::(anonymous namespace)::InvokeWithArgArray(art::ScopedObjectAccessAlreadyRunnable const&, art::ArtMethod*, art::(anonymous namespace)::ArgArray*, art::JValue*, char const*)+52)
A/DEBUG:     #42 pc 00348f15  /system/lib/libart.so (art::InvokeMethod(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jobject*, _jobject*, unsigned int)+1024)
A/DEBUG:     #43 pc 002fb0c5  /system/lib/libart.so (art::Method_invoke(_JNIEnv*, _jobject*, _jobject*, _jobjectArray*)+40)
A/DEBUG:     #44 pc 0011226f  /system/framework/arm/boot.oat (offset 0x10c000) (java.lang.Class.getDeclaredMethodInternal [DEDUPED]+110)
A/DEBUG:     #45 pc 0040d575  /system/lib/libart.so (art_quick_invoke_stub_internal+68)
A/DEBUG:     #46 pc 003e6b91  /system/lib/libart.so (art_quick_invoke_stub+224)
A/DEBUG:     #47 pc 000a1015  /system/lib/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+136)
A/DEBUG:     #48 pc 001e5ae9  /system/lib/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+236)
A/DEBUG:     #49 pc 001e05d7  /system/lib/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+814)
A/DEBUG:     #50 pc 003e17eb  /system/lib/libart.so (MterpInvokeVirtual+442)
A/DEBUG:     #51 pc 00400314  /system/lib/libart.so (ExecuteMterpImpl+14228)
A/DEBUG:     #52 pc 00c0d986  /system/framework/boot-framework.vdex (com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run+22)
A/DEBUG:     #53 pc 001c4d53  /system/lib/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.841527758+378)
A/DEBUG:     #54 pc 001c937f  /system/lib/libart.so (art::interpreter::EnterInterpreterFromEntryPoint(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*)+82)
A/DEBUG:     #55 pc 003d52d1  /system/lib/libart.so (artQuickToInterpreterBridge+880)
A/DEBUG:     #56 pc 00411aff  /system/lib/libart.so (art_quick_to_interpreter_bridge+30)
A/DEBUG:     #57 pc 00a107e5  /system/framework/arm/boot-framework.oat (offset 0x3ab000) (com.android.internal.os.ZygoteInit.main+2836)
A/DEBUG:     #58 pc 0040d575  /system/lib/libart.so (art_quick_invoke_stub_internal+68)
A/DEBUG:     #59 pc 003e6c93  /system/lib/libart.so (art_quick_invoke_static_stub+222)
A/DEBUG:     #60 pc 000a1027  /system/lib/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+154)
A/DEBUG:     #61 pc 00347ac5  /system/lib/libart.so (art::(anonymous namespace)::InvokeWithArgArray(art::ScopedObjectAccessAlreadyRunnable const&, art::ArtMethod*, art::(anonymous namespace)::ArgArray*, art::JValue*, char const*)+52)
A/DEBUG:     #62 pc 003478ef  /system/lib/libart.so (art::InvokeWithVarArgs(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, std::__va_list)+310)
A/DEBUG:     #63 pc 0028eb11  /system/lib/libart.so (art::JNI::CallStaticVoidMethodV(_JNIEnv*, _jclass*, _jmethodID*, std::__va_list)+444)
A/DEBUG:     #64 pc 0006caab  /system/lib/libandroid_runtime.so (_JNIEnv::CallStaticVoidMethod(_jclass*, _jmethodID*, ...)+30)
A/DEBUG:     #65 pc 0006ed03  /system/lib/libandroid_runtime.so (android::AndroidRuntime::start(char const*, android::Vector<android::String8> const&, bool)+458)
A/DEBUG:     #66 pc 00001989  /system/bin/app_process32 (main+728)
A/DEBUG:     #67 pc 0008afdd  /system/lib/libc.so (__libc_init+48)
A/DEBUG:     #68 pc 0000166f  /system/bin/app_process32 (_start_main+38)
A/DEBUG:     #69 pc 00000306  <anonymous:f73e9000>

**Comment by bookzhan** [comment]
@gejiashu 你把日志贴上来，你的图片挂了

**Comment by bookzhan** [comment]
@gejiashu 我会去查一下，看看代码有没有问题

**Comment by gejiashu** [comment]
好的

**Comment by bookzhan** [comment]
@gejiashu 你是不是Camera的分辨率变了，但是BZYUVUtil没有重新new? 如果是这样的话那么请更新版本到1.1.10，我在BZYUVUtil里面做了处理

**Comment by gejiashu** [comment]
是的，我中间是切换过Camera预览的分辨率，没有重新new，但是也不是每次切换分辨率都会出现这个问题。

**Comment by bookzhan** [comment]
哦，那你用这个新的应该就没有问题了，如果还有问题你再联系我

**Comment by gejiashu** [comment]
好的，我试试
