### ISSUE TITLE
bintray 要关闭了，可以发布到其他地方吗？

### ISSUE THREAD

**Issue by yangcheng** [bookzhan/bzyuvlib#3]
https://www.infoq.com/news/2021/02/jfrog-jcenter-bintray-closure/

**Comment by bookzhan** [comment]
> https://www.infoq.com/news/2021/02/jfrog-jcenter-bintray-closure/

哦这样的，那我这两天搬个家

**Comment by yangcheng** [comment]
👍🏻

**Comment by bookzhan** [comment]
已经发布到了mavenCentral了，依赖方式为implementation 'io.github.bookzhan:bzyuv:1.1.16@aar'

**Comment by bookzhan** [comment]
allprojects->repositories 里面要添加 mavenCentral()详见readme.md
