### ISSUE TITLE
如果您有时间能详细讲解一下 如何编译yublib到使用yuvlib吗，个人看不懂c++代码

### ISSUE THREAD

**Issue by gaohequan** [bookzhan/bzyuvlib#4]
native-lib.cpp  这个文件的代码是自己写的 还是yuvlib生成的
不太懂ndk jni这些东西。。

**Comment by bookzhan** [comment]
https://www.bzblog.online/wordpress/index.php/2020/05/13/142/ 编译方法请参考我之前写的博客

**Comment by gaohequan** [comment]
![4k](https://user-images.githubusercontent.com/20533279/115671735-68d59780-a37d-11eb-91cf-75cc1be1acbc.jpg)
![缩放](https://user-images.githubusercontent.com/20533279/115671752-6d9a4b80-a37d-11eb-9b5c-c449a1453a9c.jpg)

有个小问题 我是camera2获取的 NV21_4K数据；
第一个图是直接转化NV12然后存储；
第二个图是NV21先使用您的算法缩放到1080P，在从NV21_1080P转化成的NV12数据
NV21转化NV12的方法是
    private void transform_YUV_420_888(byte[] src,byte[] dest,int width,int height){
        if(src == null || dest == null)return;
        int framesize = width*height;
        System.arraycopy(src, 0, dest, 0, framesize);
        for (int i = 0; i < (framesize / 4); i++)
        {
            dest[framesize + (i * 2)] = src[(i * 2) + framesize + 1];
            dest[framesize + (i * 2) + 1] = src[(i * 2) + framesize];
        }
    }
所示每一帧的数据都失真了，是不是您的压缩算法有问题，还是我个人使用的问题。

**Comment by bookzhan** [comment]
我里面的zoom方法只是支持YUV420，你直接传入NV21是有问题的

**Comment by bookzhan** [comment]
camera2是支持直接输入YUV420的，技术方案你可以改成：

1. camera2输出YUV420
2. 通过这个方法预处理YUV preHandleYUV420(Image image, boolean flipHorizontal, int rotate)
3. 通过zoomYUV420方法缩放YUV
4. 把YUV420转换成NV12
YUV420(在这里应该是YV12或者是YV21,具体的我记不清了，你到时候看看就知道了)

**Comment by bookzhan** [comment]
你也可以直接把NV21转换成YUVI420，通过preHandleNV21

**Comment by gaohequan** [comment]
谢谢 谢谢 非常感谢 成功了！
