### ISSUE TITLE
在三星Galaxy A51 5G （android 11 ） 转化后颜色不对

### ISSUE THREAD

**Issue by gaohequan** [bookzhan/bzyuvlib#5]
1.使用mediaCodec 将mp4视频 逐帧解析成 Image
2.将image转化成nv21 预览图片正常 
3.将image转化成nv12 组成视频 视频是灰色的  失真了

**Comment by bookzhan** [comment]
与Image相关的方法我只是提供了yuv420pToRGB，不知道你是用的那个方法，怎么使用的。mediaCodec解码之后的YUV有的手机是NV21的格式，有的手机是YUV420p的格式，这个你也需要注意一下。你的问题大概率出现在视频编码的部分，因为nv21和nv21只是uv顺序是反的，具体表现为一个图像是正常的，一个图像是偏蓝的

**Comment by bookzhan** [comment]
出现灰色的图像应该是你只是把Y数据写入了，uv数据你丢掉了

**Comment by gaohequan** [comment]
i420 = mBZYUVUtil.preHandleYUV420(image,false,0)；
nv21 = BZYUVUtil.yuvI420ToNV21(i420,nv21,width,height);
i420 = BZYUVUtil.preHandleNV21(nv21,i420,width,height,false,0);
nv12 = BZYUVUtil.yuvI420ToNV12(i420,nv12,width,height);
确认数据没问题了，其他手机都正常，只有三星有问题。应该是手机的问题。

**Comment by bookzhan** [comment]
里面有这些方法，你转换成RGB在用bitmap显示出来，看看是哪里出问题了
nv21ToRGBA
nv21ToBGRA（这个方法等同于nv12ToRGBA）
yuv420ToRGBA

另外里面有yuvI420ToNV12一步到位，不用来回转换的

**Comment by gaohequan** [comment]
还有openCv的一些算法需要处理nv21的数据。
不过也单纯的使用
 i420 = mBZYUVUtil.preHandleYUV420(image,false,0)；
 nv12 = BZYUVUtil.yuvI420ToNV12(i420,nv12,width,height);
 这两个方法尝试。只有三星手机不行其他正常。应该是三星手机的问题。我在继续排查一下。

**Comment by bookzhan** [comment]
以确认一下image里面装的数据是YUV420的，有的手机mediaCodec解码后市nv21的。preHandleYUV420之后调用yuv420ToRGBA看看图像正常不

**Comment by gaohequan** [comment]
找到原因了数据本事应该是没有错的
只是使用mediaCodec编码的时候 此三星手机MediaFormat 设置Key_color_format  
需要用COLOR_FormatYUV420SemiPlanar代替COLOR_FormatYUV420Flexible
