### ISSUE TITLE
Could you add support  'x86' ,'x86_64' at this project?

### ISSUE THREAD

**Issue by kikokuo** [bookzhan/bzyuvlib#6]
Hello,
           This project is great when transfer format of Image. But this library not support x86 and x86_64.
           Could you add support  'x86' ,'x86_64' at this project? thanks.

**Comment by bookzhan** [comment]
The x86 library has been added in version 1.1.18
implementation 'com.guaishou.bzlib:bzyuv:cc@aar

**Comment by kikokuo** [comment]
It's work, thansk
