### ISSUE TITLE
我想知道怎么旋转

### ISSUE THREAD

**Issue by CaoXiLin** [bookzhan/bzyuvlib#9]
有没有YUV工具类直接调用旋转90°的

**Comment by CaoXiLin** [comment]
可以上个截图或者apk吗

**Comment by bookzhan** [comment]
你可以看一下每个方法基本都有rotate参数，你传入就好了

**Comment by CaoXiLin** [comment]
好的谢谢
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年06月24日 11:13 |
| 收件人 | bookzhan/bzyuvlib ***@***.***> |
| 抄送人 | CaoXiLin ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [bookzhan/bzyuvlib] 我想知道怎么旋转 (Issue #9) |

Closed #9 as completed.
